CREATE TABLE "STATE"(
"STATE_ID" INT PRIMARY KEY NOT NULL,
"NAME" CHAR(2) NOT NULL
);

CREATE TABLE "COLOR"(
"COLOR_ID" INT PRIMARY KEY NOT NULL,
"NAME" VARCHAR(10) NOT NULL
);

CREATE TABLE "TEAM"(
"TEAM_ID" INT PRIMARY KEY NOT NULL,
"NAME" VARCHAR(20) NOT NULL,
"STATE_ID" INT REFERENCES "STATE"("STATE_ID"),
"COLOR_ID" INT REFERENCES "COLOR"("COLOR_ID"),
"WINS" INT NOT NULL DEFAULT 0,
"LOSSES" INT NOT NULL DEFAULT 0
);

CREATE TABLE "PLAYER"(
"PLAYER_ID" INT PRIMARY KEY NOT NULL,
"TEAM_ID" INT REFERENCES "TEAM"("TEAM_ID"),
"UNIFORM_NUM" INT NOT NULL,
"FIRST_NAME" VARCHAR(20) NOT NULL,
"LAST_NAME" VARCHAR(20) NOT NULL,
"MPG" INT,
"PPG" INT,
"RPG" INT,
"APG" INT,
"SPG" DECIMAL(3,1),
"BPG" DECIMAL(3,1)
);
